--
-- PostgreSQL database dump
--

-- Dumped from database version 14.17 (Debian 14.17-1.pgdg120+1)
-- Dumped by pg_dump version 14.17 (Debian 14.17-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: boards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.boards (
    id bigint NOT NULL,
    map_image_url character varying(255),
    name character varying(255) NOT NULL,
    svg_overlay_url character varying(255)
);


--
-- Name: boards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.boards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.boards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: building_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.building_orders (
    id bigint NOT NULL,
    building_id bigint NOT NULL,
    from_sector integer NOT NULL,
    player_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    status_message character varying(500),
    to_sector integer NOT NULL,
    turn integer NOT NULL,
    CONSTRAINT building_orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RESOLVED'::character varying, 'BLOCKED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: building_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.building_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.building_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: combat_entities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.combat_entities (
    entity_type character varying(31) NOT NULL,
    id bigint NOT NULL,
    armor double precision NOT NULL,
    attack double precision NOT NULL,
    defense double precision NOT NULL,
    evasion double precision NOT NULL,
    is_destroyed boolean NOT NULL,
    pdc double precision NOT NULL,
    pdf double precision NOT NULL,
    player_id bigint,
    building_type character varying(255),
    captured_by_player_id bigint,
    captured_turn integer,
    last_moved_turn integer,
    has_moved boolean,
    stored_money double precision,
    is_operational boolean,
    max_capacity integer,
    base_armor double precision,
    base_attack double precision,
    base_defense double precision,
    base_evasion double precision,
    base_pdc double precision,
    base_pdf double precision,
    character_name character varying(100),
    experience double precision,
    is_injured boolean,
    number integer,
    type character varying(255),
    vehicle_type character varying(255),
    board_id bigint,
    sector_number integer,
    pilot_id bigint,
    vehicle_id bigint,
    CONSTRAINT combat_entities_building_type_check CHECK (((building_type)::text = ANY ((ARRAY['HEADQUARTERS'::character varying, 'WEAPON_CACHE'::character varying, 'BANK'::character varying])::text[]))),
    CONSTRAINT combat_entities_type_check CHECK (((type)::text = ANY ((ARRAY['LARBIN'::character varying, 'VOYOU'::character varying, 'MALFRAT'::character varying, 'BRUTE'::character varying, 'PERSONNAGE'::character varying])::text[]))),
    CONSTRAINT combat_entities_vehicle_type_check CHECK (((vehicle_type)::text = ANY ((ARRAY['TOURELLE'::character varying, 'VTT_LEGER'::character varying, 'VTT_BLINDE'::character varying, 'TANK'::character varying, 'HELICOPTERE'::character varying, 'AVION_TRANSPORT'::character varying])::text[])))
);


--
-- Name: combat_entities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.combat_entities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.combat_entities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: credentials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credentials (
    id bigint NOT NULL,
    password character varying(255),
    refresh_token_expiry bigint,
    refresh_token_hash character varying(255),
    refresh_token_jti character varying(255),
    role character varying(255),
    username character varying(255)
);


--
-- Name: credentials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credentials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.credentials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.equipment (
    id bigint NOT NULL,
    arm_bonus double precision NOT NULL,
    category character varying(255) NOT NULL,
    cost integer NOT NULL,
    evasion_bonus double precision NOT NULL,
    name character varying(255) NOT NULL,
    pdc_bonus double precision NOT NULL,
    pdf_bonus double precision NOT NULL,
    CONSTRAINT equipment_category_check CHECK (((category)::text = ANY ((ARRAY['FIREARM'::character varying, 'MELEE'::character varying, 'DEFENSIVE'::character varying])::text[])))
);


--
-- Name: equipment_compatible_classes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.equipment_compatible_classes (
    equipment_id bigint NOT NULL,
    unit_class character varying(255),
    CONSTRAINT equipment_compatible_classes_unit_class_check CHECK (((unit_class)::text = ANY ((ARRAY['LEGER'::character varying, 'ELEMENTAIRE'::character varying, 'TIREUR'::character varying, 'MASTODONTE'::character varying, 'PILOTE_DESTRUCTEUR'::character varying, 'SNIPER'::character varying])::text[])))
);


--
-- Name: equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.equipment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipment_stacks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.equipment_stacks (
    id bigint NOT NULL,
    available integer NOT NULL,
    quantity integer NOT NULL,
    equipment_id bigint NOT NULL,
    player_id bigint NOT NULL,
    weapon_cache_id bigint
);


--
-- Name: equipment_stacks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.equipment_stacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_stacks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movement_order_entities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movement_order_entities (
    order_id bigint NOT NULL,
    entity_id bigint
);


--
-- Name: movement_order_route; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movement_order_route (
    order_id bigint NOT NULL,
    sector_number integer,
    route_index integer NOT NULL
);


--
-- Name: movement_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movement_orders (
    id bigint NOT NULL,
    from_sector integer NOT NULL,
    player_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    status_message character varying(500),
    to_sector integer NOT NULL,
    turn integer NOT NULL,
    vehicle_id bigint,
    CONSTRAINT movement_orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RESOLVED'::character varying, 'BLOCKED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: movement_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.movement_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movement_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: player_resources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.player_resources (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    resource_name character varying(255) NOT NULL,
    player_id bigint NOT NULL,
    resource_id bigint,
    bank_id bigint
);


--
-- Name: player_resources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.player_resources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_resources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: players; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.players (
    id bigint NOT NULL,
    armor_bonus_percent double precision,
    attack_bonus_percent double precision,
    defense_bonus_percent double precision,
    evasion_bonus_percent double precision,
    pdc_bonus_percent double precision,
    pdf_bonus_percent double precision,
    name character varying(255) NOT NULL,
    global_power double precision,
    money double precision,
    total_armor double precision,
    total_atk double precision,
    total_def double precision,
    total_defensive_power double precision,
    total_economy_power double precision,
    total_equipment_value double precision,
    total_income double precision,
    total_offensive_power double precision,
    total_pdc double precision,
    total_pdf double precision,
    total_vehicles_value double precision,
    user_id bigint,
    character_id bigint
);


--
-- Name: players_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.players ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.players_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource (
    id bigint NOT NULL,
    base_value double precision NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: resource_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resource ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resource_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sector_neighbors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sector_neighbors (
    board_id bigint NOT NULL,
    sector_number integer NOT NULL,
    neighbor_number integer
);


--
-- Name: sectors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sectors (
    board_id bigint NOT NULL,
    number integer NOT NULL,
    color character varying(255) NOT NULL,
    income double precision NOT NULL,
    name character varying(255) NOT NULL,
    owner_id bigint,
    resource_name character varying(255),
    sector_global_stats double precision,
    sector_total_armor double precision,
    sector_total_atk double precision,
    sector_total_def double precision,
    sector_total_defensive double precision,
    sector_total_offensive double precision,
    sector_total_pdc double precision,
    sector_total_pdf double precision,
    x integer,
    y integer
);


--
-- Name: unit_classes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unit_classes (
    unit_id bigint NOT NULL,
    unit_class character varying(255),
    CONSTRAINT unit_classes_unit_class_check CHECK (((unit_class)::text = ANY ((ARRAY['LEGER'::character varying, 'ELEMENTAIRE'::character varying, 'TIREUR'::character varying, 'MASTODONTE'::character varying, 'PILOTE_DESTRUCTEUR'::character varying, 'SNIPER'::character varying])::text[])))
);


--
-- Name: unit_equipments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unit_equipments (
    id bigint NOT NULL,
    equipment_id bigint NOT NULL,
    unit_id bigint NOT NULL
);


--
-- Name: unit_equipments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.unit_equipments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unit_equipments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: boards boards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boards
    ADD CONSTRAINT boards_pkey PRIMARY KEY (id);


--
-- Name: building_orders building_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_orders
    ADD CONSTRAINT building_orders_pkey PRIMARY KEY (id);


--
-- Name: combat_entities combat_entities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.combat_entities
    ADD CONSTRAINT combat_entities_pkey PRIMARY KEY (id);


--
-- Name: credentials credentials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credentials
    ADD CONSTRAINT credentials_pkey PRIMARY KEY (id);


--
-- Name: equipment equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_pkey PRIMARY KEY (id);


--
-- Name: equipment_stacks equipment_stacks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_stacks
    ADD CONSTRAINT equipment_stacks_pkey PRIMARY KEY (id);


--
-- Name: movement_order_route movement_order_route_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movement_order_route
    ADD CONSTRAINT movement_order_route_pkey PRIMARY KEY (order_id, route_index);


--
-- Name: movement_orders movement_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movement_orders
    ADD CONSTRAINT movement_orders_pkey PRIMARY KEY (id);


--
-- Name: player_resources player_resources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_resources
    ADD CONSTRAINT player_resources_pkey PRIMARY KEY (id);


--
-- Name: players players_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_pkey PRIMARY KEY (id);


--
-- Name: resource resource_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource
    ADD CONSTRAINT resource_pkey PRIMARY KEY (id);


--
-- Name: sectors sectors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sectors
    ADD CONSTRAINT sectors_pkey PRIMARY KEY (board_id, number);


--
-- Name: boards uk7pat9n19tjsdksl6c01d0rjtn; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boards
    ADD CONSTRAINT uk7pat9n19tjsdksl6c01d0rjtn UNIQUE (name);


--
-- Name: resource ukd6h79laa5s8cs2tqvf7ib5klb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource
    ADD CONSTRAINT ukd6h79laa5s8cs2tqvf7ib5klb UNIQUE (name);


--
-- Name: players ukfuu3xy97ynyb4ncy1sgqfnecd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT ukfuu3xy97ynyb4ncy1sgqfnecd UNIQUE (character_id);


--
-- Name: combat_entities ukk383eb2cw0bbutjd8c6xfg1hu; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.combat_entities
    ADD CONSTRAINT ukk383eb2cw0bbutjd8c6xfg1hu UNIQUE (pilot_id);


--
-- Name: equipment ukm6whtgwe6ya84f59coio1j1wh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT ukm6whtgwe6ya84f59coio1j1wh UNIQUE (name);


--
-- Name: players ukpblmuavgrnr991e41662asko; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT ukpblmuavgrnr991e41662asko UNIQUE (name);


--
-- Name: players ukr2bdiqerficgwok3omt8rwlxb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT ukr2bdiqerficgwok3omt8rwlxb UNIQUE (user_id);


--
-- Name: combat_entities ukti530xb422xy1qvtwp3gufvf8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.combat_entities
    ADD CONSTRAINT ukti530xb422xy1qvtwp3gufvf8 UNIQUE (character_name);


--
-- Name: unit_equipments unit_equipments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_equipments
    ADD CONSTRAINT unit_equipments_pkey PRIMARY KEY (id);


--
-- Name: idx_refresh_token_jti; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_token_jti ON public.credentials USING btree (refresh_token_jti);


--
-- Name: equipment_stacks fk1n8w70lkvydwjk429a1pal1jc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_stacks
    ADD CONSTRAINT fk1n8w70lkvydwjk429a1pal1jc FOREIGN KEY (equipment_id) REFERENCES public.equipment(id);


--
-- Name: combat_entities fk2570jvuu09weacray8up21v0g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.combat_entities
    ADD CONSTRAINT fk2570jvuu09weacray8up21v0g FOREIGN KEY (board_id, sector_number) REFERENCES public.sectors(board_id, number);


--
-- Name: player_resources fk2dx9iqi45ofkqxfmj934bh95; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_resources
    ADD CONSTRAINT fk2dx9iqi45ofkqxfmj934bh95 FOREIGN KEY (bank_id) REFERENCES public.combat_entities(id);


--
-- Name: combat_entities fk3rcshxej009rm2rwdw24fijjm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.combat_entities
    ADD CONSTRAINT fk3rcshxej009rm2rwdw24fijjm FOREIGN KEY (pilot_id) REFERENCES public.combat_entities(id);


--
-- Name: unit_classes fk8no0gop0jpo3hf2c8jag94rtt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_classes
    ADD CONSTRAINT fk8no0gop0jpo3hf2c8jag94rtt FOREIGN KEY (unit_id) REFERENCES public.combat_entities(id);


--
-- Name: unit_equipments fk8nq4cv16iq9am2hcwp76dpq9n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_equipments
    ADD CONSTRAINT fk8nq4cv16iq9am2hcwp76dpq9n FOREIGN KEY (unit_id) REFERENCES public.combat_entities(id);


--
-- Name: player_resources fka8hm2fe0ug41s8rty9gyb5j1j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_resources
    ADD CONSTRAINT fka8hm2fe0ug41s8rty9gyb5j1j FOREIGN KEY (player_id) REFERENCES public.players(id);


--
-- Name: sectors fkbjulvsqr9wl3odc50gib90oog; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sectors
    ADD CONSTRAINT fkbjulvsqr9wl3odc50gib90oog FOREIGN KEY (board_id) REFERENCES public.boards(id);


--
-- Name: sector_neighbors fkch424qh31otl10pi3mrsbpt0v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sector_neighbors
    ADD CONSTRAINT fkch424qh31otl10pi3mrsbpt0v FOREIGN KEY (board_id, sector_number) REFERENCES public.sectors(board_id, number);


--
-- Name: equipment_compatible_classes fkcpoycmbql3wohfcsuvgasrmlm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_compatible_classes
    ADD CONSTRAINT fkcpoycmbql3wohfcsuvgasrmlm FOREIGN KEY (equipment_id) REFERENCES public.equipment(id);


--
-- Name: equipment_stacks fkd6983pjf9v0x0ln0jmff57xy2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_stacks
    ADD CONSTRAINT fkd6983pjf9v0x0ln0jmff57xy2 FOREIGN KEY (weapon_cache_id) REFERENCES public.combat_entities(id);


--
-- Name: combat_entities fkg0hxdkfufa8ry3dwxmkqjqdw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.combat_entities
    ADD CONSTRAINT fkg0hxdkfufa8ry3dwxmkqjqdw FOREIGN KEY (vehicle_id) REFERENCES public.combat_entities(id);


--
-- Name: equipment_stacks fkgflf34m8jy0q85dm7v3t86oap; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_stacks
    ADD CONSTRAINT fkgflf34m8jy0q85dm7v3t86oap FOREIGN KEY (player_id) REFERENCES public.players(id);


--
-- Name: movement_order_entities fkipje0p4801r0ypalqnsfefa9j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movement_order_entities
    ADD CONSTRAINT fkipje0p4801r0ypalqnsfefa9j FOREIGN KEY (order_id) REFERENCES public.movement_orders(id);


--
-- Name: player_resources fklb09jo763lxoqm07i49tmiqnk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.player_resources
    ADD CONSTRAINT fklb09jo763lxoqm07i49tmiqnk FOREIGN KEY (resource_id) REFERENCES public.resource(id);


--
-- Name: unit_equipments fkmcbllea0d3hxur3qchs1e7rl2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_equipments
    ADD CONSTRAINT fkmcbllea0d3hxur3qchs1e7rl2 FOREIGN KEY (equipment_id) REFERENCES public.equipment(id);


--
-- Name: players fkn9x2tj0f8vjnwphcidiu8r55l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT fkn9x2tj0f8vjnwphcidiu8r55l FOREIGN KEY (character_id) REFERENCES public.combat_entities(id);


--
-- Name: movement_order_route fkqx5udicsg479xlkbg2u2c8e3m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movement_order_route
    ADD CONSTRAINT fkqx5udicsg479xlkbg2u2c8e3m FOREIGN KEY (order_id) REFERENCES public.movement_orders(id);


--
-- Name: combat_entities fkt4v7d5knhovcpqn3aoy0c0mmj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.combat_entities
    ADD CONSTRAINT fkt4v7d5knhovcpqn3aoy0c0mmj FOREIGN KEY (player_id) REFERENCES public.players(id);


--
-- PostgreSQL database dump complete
--

