-- Passage en SEQUENCE (allocationSize=50) pour activer le batching d'INSERTs Hibernate.
-- Les sequences *_id_seq existent déjà (GENERATED BY DEFAULT AS IDENTITY en V1).
-- Calage de chaque sequence sur max(id) (sécurité : rows insérés hors-sequence
-- via imports explicites auraient laissé la sequence en retard), puis INCREMENT 50
-- pour matcher @SequenceGenerator(allocationSize=50) sur les entités.
-- ponytail: ceiling = un seul INSERT batched ne sert à rien ; le gain est sur
-- les imports de masse (startup importer ~150-300 INSERTs par joueur).
DO $$
DECLARE
    t text;
    seq_name text;
    max_id bigint;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'boards','building_orders','combat_entities','credentials',
        'equipment','equipment_stacks','movement_orders','player_resources',
        'players','resource','unit_equipments'
    ] LOOP
        seq_name := t || '_id_seq';
        EXECUTE format('SELECT COALESCE((SELECT max(id) FROM %I), 1)', t) INTO max_id;
        EXECUTE format('SELECT setval(%L, %s)', seq_name, max_id);
        EXECUTE format('ALTER SEQUENCE %I INCREMENT BY 50', seq_name);
    END LOOP;
END $$;
