-- Complétion du passage SEQUENCE initié en V4.
-- V1__baseline.sql (et l'ancien ddl-auto=update IDENTITY) créent chaque PK en
-- GENERATED BY DEFAULT AS IDENTITY : la séquence *_id_seq est alors une séquence
-- identité, que PostgreSQL exclut de information_schema.sequences. Hibernate
-- (ddl-auto=validate + @SequenceGenerator) ne la voit pas -> "missing sequence".
-- On convertit chaque colonne identité en colonne classique defaultée par
-- nextval sur une séquence standalone (même nom, INCREMENT 50 = allocationSize),
-- visible par Hibernate. setval sur max(id) pour ne pas réutiliser d'ids.
DO $$
DECLARE
    t text;
    seq text;
    max_id bigint;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'boards','building_orders','combat_entities','credentials',
        'equipment','equipment_stacks','movement_orders','player_resources',
        'players','resource','unit_equipments'
    ] LOOP
        seq := t || '_id_seq';
        EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id DROP IDENTITY IF EXISTS', t);
        EXECUTE format('CREATE SEQUENCE IF NOT EXISTS public.%I START WITH 1', seq);
        EXECUTE format('ALTER SEQUENCE public.%I INCREMENT BY 50', seq);
        EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id SET DEFAULT nextval(%L)', t, 'public.' || seq);
        EXECUTE format('ALTER SEQUENCE public.%I OWNED BY public.%I.id', seq, t);
        EXECUTE format('SELECT COALESCE((SELECT max(id) FROM public.%I), 1)', t) INTO max_id;
        EXECUTE format('SELECT setval(%L, %s)', 'public.' || seq, max_id);
    END LOOP;
END $$;
